-- OpsPilot LIVE Supabase schema (discovered from the project tables).
-- App IDs are UUIDs. Extra incident fields live in incident_evidence snapshots.

-- incidents
-- id uuid PK
-- incident_type text
-- service text
-- title text
-- description text
-- status text  -- open | investigating | awaiting_approval | remediating | resolved | failed
-- created_at, updated_at, resolved_at timestamptz
-- recovery_duration_seconds integer

-- incident_evidence
-- id uuid PK
-- incident_id uuid FK
-- evidence_type text  -- logs | metrics | deployment | service_status | health | other
-- data jsonb
-- collected_at timestamptz
-- OpsPilot stores a row with evidence_type='other', data.kind='opspilot_snapshot'
-- for severity/source/report and other fields not on incidents.

-- incident_investigations
-- id uuid PK
-- incident_id uuid FK
-- root_cause text
-- confidence numeric
-- evidence_summary text
-- investigation_summary text
-- recommended_action_type text
-- recommended_service text
-- recommended_version text
-- recommended_reason text
-- ai_provider text
-- created_at timestamptz

-- remediation_actions
-- id uuid PK
-- incident_id uuid FK
-- investigation_id uuid null
-- action_type text
-- service text
-- version text
-- approval_status text  -- pending | approved | rejected
-- execution_status text -- pending | running | success | failed
-- execution_result jsonb
-- approved_at, executed_at, created_at timestamptz

-- incident_history (verified recoveries only)
-- id uuid PK
-- incident_id uuid
-- incident_type, service, root_cause text
-- confidence numeric
-- evidence_summary text
-- action_type, action_target, action_result, verification_result text
-- recovery_duration_seconds integer
-- resolved_at, created_at timestamptz

-- resilience_tests
-- id uuid PK
-- scenario text
-- incident_id uuid
-- status text -- pending | running | passed | failed
-- detection_status, investigation_status, remediation_status, verification_status
--   -- pending | success | failed
-- approval_status -- pending | approved | rejected
-- recovery_duration_seconds integer
-- failure_reason text
-- started_at, completed_at, created_at timestamptz

-- resilience_test_results
-- id uuid PK
-- test_id uuid FK
-- expected_action, actual_action, expected_service, actual_service text
-- detection_success, investigation_success, remediation_success, verification_success boolean
-- details jsonb
-- created_at timestamptz
